-- Start/end-position photos for the shared exercise library, shown as a two-frame demo.
--
-- The photos come from free-exercise-db (github.com/yuhonas/free-exercise-db), released into the
-- public domain under the Unlicense. They are resized copies served from the app's own
-- /public/exercise-demos/<source id>/{0,1}.webp, so nothing is hot-linked. Each library exercise
-- is matched by hand to the same movement in that dataset; exercises with no faithful match
-- (e.g. Burpee, Landmine Press) are left without images rather than shown a different lift.
alter table exercises
  add column demo_images text[]
    check (
      demo_images is null
      -- 1–4 frames, each a site-relative path (no external hosts).
      or (cardinality(demo_images) between 1 and 4 and array_to_string(demo_images, ' ') ~ '^(/[^/\s]\S* ?)+$')
    );

update exercises e
set demo_images = array[
  '/exercise-demos/' || m.source_id || '/0.webp',
  '/exercise-demos/' || m.source_id || '/1.webp'
]
from (values
  ('Ab Wheel Rollout', 'Barbell_Ab_Rollout_-_On_Knees'),
  ('Arnold Press', 'Arnold_Dumbbell_Press'),
  ('Assault Bike', 'Air_Bike'),
  ('Assisted Pull-Up', 'Band_Assisted_Pull-Up'),
  ('Back Extension', 'Hyperextensions_Back_Extensions'),
  ('Back Squat', 'Barbell_Squat'),
  ('Band Lateral Walk', 'Monster_Walk'),
  ('Band Pull-Apart', 'Band_Pull_Apart'),
  ('Banded Face Pull', 'Face_Pull'),
  ('Barbell Bench Press', 'Barbell_Bench_Press_-_Medium_Grip'),
  ('Barbell Curl', 'Barbell_Curl'),
  ('Barbell Row', 'Bent_Over_Barbell_Row'),
  ('Bench Dip', 'Bench_Dips'),
  ('Box Jump', 'Front_Box_Jump'),
  ('Box Squat', 'Box_Squat'),
  ('Bulgarian Split Squat', 'Split_Squat_with_Dumbbells'),
  ('Cable Crossover', 'Cable_Crossover'),
  ('Cable Crunch', 'Cable_Crunch'),
  ('Cable Curl', 'Standing_Biceps_Cable_Curl'),
  ('Cable Kickback', 'One-Legged_Cable_Kickback'),
  ('Cable Lateral Raise', 'Cable_Seated_Lateral_Raise'),
  ('Cable Overhead Tricep Extension', 'Cable_Rope_Overhead_Triceps_Extension'),
  ('Cable Pull-Through', 'Pull_Through'),
  ('Calf Raise', 'Standing_Calf_Raises'),
  ('Chest Fly', 'Flat_Bench_Cable_Flyes'),
  ('Chin-Up', 'Chin-Up'),
  ('Close-Grip Bench Press', 'Close-Grip_Barbell_Bench_Press'),
  ('Concentration Curl', 'Concentration_Curls'),
  ('Crunch', 'Crunches'),
  ('Cycling', 'Bicycling'),
  ('Dead Bug', 'Dead_Bug'),
  ('Deadlift', 'Barbell_Deadlift'),
  ('Decline Bench Press', 'Decline_Barbell_Bench_Press'),
  ('Decline Push-Up', 'Decline_Push-Up'),
  ('Dip', 'Dips_-_Triceps_Version'),
  ('Dumbbell Bench Press', 'Dumbbell_Bench_Press'),
  ('Dumbbell Curl', 'Dumbbell_Bicep_Curl'),
  ('Dumbbell Fly', 'Dumbbell_Flyes'),
  ('Dumbbell Shoulder Press', 'Dumbbell_Shoulder_Press'),
  ('EZ-Bar Curl', 'EZ-Bar_Curl'),
  ('Elliptical', 'Elliptical_Trainer'),
  ('Face Pull', 'Face_Pull'),
  ('Farmer''s Carry', 'Farmers_Walk'),
  ('Front Squat', 'Front_Barbell_Squat'),
  ('Glute Bridge', 'Barbell_Glute_Bridge'),
  ('Goblet Squat', 'Goblet_Squat'),
  ('Good Morning', 'Good_Morning'),
  ('Hack Squat', 'Hack_Squat'),
  ('Hammer Curl', 'Hammer_Curls'),
  ('Hanging Knee Raise', 'Hanging_Leg_Raise'),
  ('Hanging Leg Raise', 'Hanging_Leg_Raise'),
  ('Hip Adduction', 'Band_Hip_Adductions'),
  ('Hip Thrust', 'Barbell_Hip_Thrust'),
  ('Incline Barbell Bench Press', 'Barbell_Incline_Bench_Press_-_Medium_Grip'),
  ('Incline Dumbbell Curl', 'Incline_Dumbbell_Curl'),
  ('Incline Dumbbell Press', 'Incline_Dumbbell_Press'),
  ('Incline Push-Up', 'Incline_Push-Up'),
  ('Inverted Row', 'Inverted_Row'),
  ('Jump Rope', 'Rope_Jumping'),
  ('Kettlebell Clean and Press', 'Clean_and_Press'),
  ('Kettlebell Goblet Squat', 'Goblet_Squat'),
  ('Kettlebell Swing', 'One-Arm_Kettlebell_Swings'),
  ('Lat Pulldown', 'Wide-Grip_Lat_Pulldown'),
  ('Lateral Raise', 'Side_Lateral_Raise'),
  ('Leg Curl', 'Lying_Leg_Curls'),
  ('Leg Extension', 'Leg_Extensions'),
  ('Leg Press', 'Leg_Press'),
  ('Lunge', 'Dumbbell_Lunges'),
  ('Machine Chest Press', 'Machine_Bench_Press'),
  ('Machine Shoulder Press', 'Machine_Shoulder_Military_Press'),
  ('Mountain Climber', 'Mountain_Climbers'),
  ('Neutral-Grip Pulldown', 'Close-Grip_Front_Lat_Pulldown'),
  ('Nordic Hamstring Curl', 'Natural_Glute_Ham_Raise'),
  ('Overhead Press', 'Standing_Military_Press'),
  ('Pallof Press', 'Pallof_Press'),
  ('Pec Deck', 'Butterfly'),
  ('Plank', 'Plank'),
  ('Power Clean', 'Power_Clean'),
  ('Preacher Curl', 'Preacher_Curl'),
  ('Pull-Up', 'Pullups'),
  ('Push Press', 'Push_Press'),
  ('Push-Up', 'Pushups'),
  ('Rack Pull', 'Rack_Pulls'),
  ('Rear Delt Fly', 'Cable_Rear_Delt_Fly'),
  ('Reverse Lunge', 'Dumbbell_Rear_Lunge'),
  ('Reverse Pec Deck', 'Reverse_Machine_Flyes'),
  ('Romanian Deadlift', 'Romanian_Deadlift'),
  ('Rowing Machine', 'Rowing_Stationary'),
  ('Russian Twist', 'Russian_Twist'),
  ('Seated Cable Row', 'Seated_Cable_Rows'),
  ('Seated Calf Raise', 'Seated_Calf_Raise'),
  ('Seated Leg Curl', 'Seated_Leg_Curl'),
  ('Shrug', 'Barbell_Shrug'),
  ('Side Plank', 'Side_Bridge'),
  ('Single-Arm Dumbbell Row', 'One-Arm_Dumbbell_Row'),
  ('Skull Crusher', 'EZ-Bar_Skullcrusher'),
  ('Sled Push', 'Sled_Push'),
  ('Smith Machine Squat', 'Smith_Machine_Squat'),
  ('Stair Climber', 'Stairmaster'),
  ('Standing Calf Raise', 'Standing_Calf_Raises'),
  ('Step-Up', 'Dumbbell_Step_Ups'),
  ('Straight-Arm Pulldown', 'Straight-Arm_Pulldown'),
  ('Sumo Deadlift', 'Sumo_Deadlift'),
  ('T-Bar Row', 'Bent_Over_Two-Arm_Long_Bar_Row'),
  ('Trap Bar Deadlift', 'Trap_Bar_Deadlift'),
  ('Treadmill Run', 'Running_Treadmill'),
  ('Tricep Kickback', 'Tricep_Dumbbell_Kickback'),
  ('Tricep Pushdown', 'Triceps_Pushdown'),
  ('Turkish Get-Up', 'Kettlebell_Turkish_Get-Up_Squat_style'),
  ('Upright Row', 'Upright_Barbell_Row'),
  ('Walking Lunge', 'Bodyweight_Walking_Lunge'),
  ('Wrist Curl', 'Seated_Palm-Up_Barbell_Wrist_Curl')
) as m(name, source_id)
where e.user_id is null and e.name = m.name;
